name: Publish AOSP Clang

on:
  workflow_dispatch: # 手动触发

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须赋予写入权限才能创建 Release

    steps:
      - name: Download AOSP Clang
        run: |
          # 下载文件
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-release/clang-r547379.tar.gz -O clang-r547379.tar.gz
          
          # 简单校验一下文件是否下载成功
          if [ ! -f clang-r547379.tar.gz ]; then
            echo "Error: Download failed"
            exit 1
          fi
          echo "File downloaded successfully."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: clang-r547379
          name: AOSP Clang r547379
          body: "Automatically downloaded AOSP Clang r547379 from Android source."
          files: clang-r547379.tar.gz
          draft: false
          prerelease: false
